use std::path::{Path, PathBuf};

fn depo() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("depo kökü")
        .to_path_buf()
}

fn oku(goreli: &str) -> String {
    std::fs::read_to_string(depo().join(goreli)).expect("depo dosyası okunmalı")
}

#[test]
fn registry_lock_girdilerinin_sha256_ozeti_zorunludur() {
    for yol in ["compiler/Cargo.lock", "compiler/fuzz/Cargo.lock"] {
        let kilit = oku(yol);
        assert!(kilit.starts_with("# This file is automatically @generated by Cargo.\n"));
        assert!(kilit.contains("\nversion = 4\n"), "{yol}");

        let mut registry_paketi = 0;
        for paket in kilit.split("[[package]]").skip(1) {
            if !paket.contains("source = \"registry+") {
                continue;
            }
            registry_paketi += 1;
            assert!(
                paket
                    .contains("source = \"registry+https://github.com/rust-lang/crates.io-index\""),
                "{yol}: yalnız crates.io registry kaynağı kabul edilir: {paket}"
            );
            let ozet = paket
                .lines()
                .find_map(|satir| {
                    satir
                        .strip_prefix("checksum = \"")
                        .and_then(|s| s.strip_suffix('"'))
                })
                .expect("registry paketi checksum taşımalı");
            assert_eq!(ozet.len(), 64, "checksum SHA-256 uzunluğunda olmalı");
            assert!(
                ozet.bytes()
                    .all(|bayt| bayt.is_ascii_hexdigit() && !bayt.is_ascii_uppercase()),
                "checksum küçük hex olmalı"
            );
        }
        assert!(
            registry_paketi > 50,
            "{yol}: beklenmedik ölçüde küçük registry grafiği"
        );
    }
}

#[test]
fn cargo_deny_politikasi_fail_closed_ve_istisnalari_gerekcelidir() {
    let manifest = oku("compiler/Cargo.toml");
    let fuzz_manifesti = oku("compiler/fuzz/Cargo.toml");
    let politika = oku("compiler/deny.toml");
    assert!(manifest.contains("publish = false"));
    assert!(fuzz_manifesti.contains("publish = false"));
    assert!(fuzz_manifesti.contains("version = \"=0.7.0\""));
    assert!(politika.contains("unknown-registry = \"deny\""));
    assert!(politika.contains("unknown-git = \"deny\""));
    assert!(politika.contains("multiple-versions = \"deny\""));
    assert!(politika.contains("wildcards = \"deny\""));
    assert!(politika.contains("ignore = []"));
    for satir in politika.lines().filter(|satir| satir.contains("crate = ")) {
        assert!(satir.contains("reason = "), "istisna gerekçesiz: {satir}");
    }
}

#[test]
fn ci_sabit_aracla_guncel_advisory_ve_offline_vendor_kapisi_kosar() {
    let ci = oku(".github/workflows/tedarik.yml");
    assert!(ci.contains("cargo install cargo-deny --version 0.20.2 --locked"));
    assert!(ci.contains("actions/checkout@11d5960a326750d5838078e36cf38b85af677262"));
    assert!(ci.contains("cargo deny --locked check -D warnings"));
    assert!(ci.contains("--manifest-path fuzz/Cargo.toml --config deny.toml"));
    assert!(ci.contains("schedule:"));
    assert!(ci.contains("bash scripts/offline-vendor-denetle.sh"));

    let ana_ci = oku(".github/workflows/ci.yml");
    assert!(!ana_ci.contains("cargo test --locked || cargo test"));
    for komut in [
        "cargo test",
        "cargo build",
        "cargo clippy",
        "cargo check",
        "cargo run",
        "cargo rustc",
    ] {
        for satir in ana_ci.lines().filter(|satir| satir.contains(komut)) {
            assert!(satir.contains("--locked"), "kilitsiz CI komutu: {satir}");
        }
    }
}

#[test]
fn vendor_kaniti_iki_uretimi_ve_bos_cargo_home_offline_derlemeyi_ister() {
    let betik = oku("scripts/offline-vendor-denetle.sh");
    assert!(betik.contains("cargo vendor --locked --versioned-dirs"));
    assert!(betik.contains("--sync \"$fuzz_manifesti\""));
    assert!(betik.contains("for tur in bir iki"));
    assert!(betik.contains("cmp -s"));
    assert!(betik.contains("CARGO_HOME="));
    assert!(betik.contains("CARGO_NET_OFFLINE=true"));
    assert!(betik.contains("cargo check --quiet --locked --offline --all-targets --all-features"));
    assert!(betik.contains("cargo check --quiet --locked --offline --bins"));
    assert!(oku(".gitignore").lines().any(|satir| satir == "**/vendor/"));
}
